export const agentState = {
  mainWindow: null,
  ipcHandlersRegistered: false,
  latestPrinterResult: null,
  heartbeatTimer: null,
  printerSyncTimer: null,
  jobPollTimer: null,
  predownloadTimer: null,
  conversionTimer: null,
  isPollingJobs: false,
  isPredownloading: false,
  isConverting: false,
  cachedHubUrl: "",
};

export const agentSession = {
  deviceId: "",
  deviceName: "",
  pairingCode: "",
  pairingSessionId: "",
  expiresAt: "",
  agentId: "",
  hubId: "",
  accessToken: "",
  pairedAt: "",
  lastHeartbeatAt: "",
  lastHeartbeatError: "",
  selectedPrinterName: "",
  lastPrinterSyncAt: "",
  lastPrinterSyncError: "",
  lastJobPollAt: "",
  lastJobPollError: "",
  lastJobPollMessage: "",
  predownloadRunning: false,
  predownloadLoopRunning: false,
  lastPredownloadAt: "",
  lastPredownloadError: "",
  lastPredownloadMessage: "",
  conversionRunning: false,
  conversionLoopRunning: false,
  lastConversionAt: "",
  lastConversionError: "",
  lastConversionMessage: "",
  restored: false,
};
