export const appState = {
  mainWindow: null,
  ipcHandlersRegistered: false,
  latestPrinterResult: null,
  heartbeatTimer: null,
  printerSyncTimer: null,
  jobPollTimer: null,
  predownloadTimer: null,
  conversionTimer: null,
  isPollingJobs: false,
  isPredownloading: false,
  isConverting: false,
  agentSession: {
    hubId: null,
    hubToken: null,
    hubUrl: null,
    hubName: null,
    deviceId: null,
    status: "idle",
    lastHeartbeat: null,
    lastHeartbeatError: null,
    lastPrinterSync: null,
    lastPrinterSyncError: null,
    lastJobPoll: null,
    lastJobPollError: null,
    lastPredownload: null,
    lastPredownloadError: null,
  }
};
